### ISSUE TITLE
Create the AWS Organizations environment setup (based on research).

### ISSUE THREAD

**Issue by henkberendsen** [GiPHouse/giphouse-website-spring2023#12]
### One sentence description
Create the AWS Organizations environment setup (based on research).

### Suggested implementation. 
Use boto3 and moto3 to create functions to create Organizational Units, Member Accounts etc.

**Comment by henkberendsen** [comment]
boto3 functions which may be useful:
create_account()
create_organization()
create_organizational_unit()

describe_organization()
describe_organizational_unit()

list_accounts()
list_accounts_for_parent()
list_children()
list_parents()
list_roots()

move_account()

update_organizational_unit()

**Comment by 1058274** [comment]
Based on the decisions made in #6 :).

**Comment by 1058274** [comment]
For some of the listed functions above (particularly those starting with `list_`), the entire result of a request may not fit in a single response. This is what the `NextToken` parameter is for, which you might have seen in documentation. It is easiest to deal with this using *Paginators*, which will return an iterator for the (multiple) responses. See the following for more details:
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations.html#paginators
- https://boto3.amazonaws.com/v1/documentation/api/latest/guide/paginators.html

**Comment by Jer111** [comment]
- Create the organzational units (create_OU()) - Henk & Jermo
- Invite users to the units (move_account()) - Filip
- Create course iteration unit (create_organizatal_unit()) - Henk & Jermo

**Comment by mitchellboes** [comment]
Please add tags to the OU's you create (project_slug, project_semester as keys). You can pass it as an argument to the create_organizational_unit function.

**Comment by flam123** [comment]
I will work on the test_awssync.py file

**Comment by 1058274** [comment]
If you accept a pull request, also close its corresponding issue (this one was open).
