### ISSUE TITLE
Extract relevant synchronization data (accounts, units) from current AWS environment.

### ISSUE THREAD

**Issue by flam123** [GiPHouse/giphouse-website-spring2023#17]

**Comment by flam123** [comment]
## One sentence description
Extract the list of teams (organizational units) from AWS and present it in a format that makes it possible to compare with the data present on Django.

## Suggested implementation
Research on what AWS function are applicable for this issue and use them in the implementation. Moto3 maybe  a useful tool for testing those functions

**Comment by flam123** [comment]
To work on this further we either need to have the structure already in AWS or make it our self

**Comment by mitchellboes** [comment]
I made a class/struct you can use to store the AWS data in. It is called "AWSTree" and you can find it in the code on branch 26-sync-edge-cases (in projects -> awssync.py). I also created a function to convert from AWSTree to a list of SyncData elements.
