### ISSUE TITLE
Research SCP configuration for AWS Organizations

### ISSUE THREAD

**Issue by henkberendsen** [GiPHouse/giphouse-website-spring2023#24]
### One sentence description
Do research on SCP policies and IAM users in order to give organization members the correct permissions.

### Documentation
https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users.html
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html

https://aws.amazon.com/blogs/security/how-to-use-service-control-policies-to-set-permission-guardrails-across-accounts-in-your-aws-organization/

**Comment by Jer111** [comment]
# SCP policies for the AWS account
In the AWS account under the policies tab, you can create JSON files with policies. 

https://aws.amazon.com/blogs/security/how-to-use-service-control-policies-to-set-permission-guardrails-across-accounts-in-your-aws-organization/

After creating a policy it looks something like this:
```JSON
{
    "Version"  : "2012-10-17",
    "Statement": [
        {
            "Sid"   : "Stmt1234567890",
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

This is a policy that allows the user to list all s3 buckets and list the contents of a bucket. 
- The "Sid" is a unique identifier for the policy.
- The "Effect" is either "Allow" or "Deny".
- The "Action" is the action that is allowed or denied.
- The "Resource" is the resource that the action is allowed or denied on.


So for every action you want to allow or deny, you need to create a new policy.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations/client/create_policy.html

With boto3 the policies can be created like this:
```python
response = client.create_policy(
    Content='JSON file escaped with backslashes see documentation',
    Description='Description of the policy',
    Name='Name of the policy',
    Type='SERVICE_CONTROL_POLICY'
)
```

These policies can then be attached to an user or organization unit.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations/client/attach_policy.html

```python
response = client.attach_policy(
    PolicyId='Policy ID',
    TargetId='Target ID'
)
```

To get working with the scp, you need to enable scp usage for the root organization. This can be done using the enable_policy_type function. 

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations/client/enable_policy_type.html

**Comment by henkberendsen** [comment]
# Plan for IAM based on research
**Note: we are not sure yet if we will need IAM policies in our project. If we decide not to add IAM users under each mailing member account (it was a suggestion of the client that we could maybe do this), it could be that SCP policies are sufficient to give the correct permissions.**

## Structure
- For each mailing list member account, create IAM users. One IAM user per student in the team. 

## User setup
- Give the IAM users a console password as credentials, this allows them to log into the AWS Management Console, a web application that seems like the most user-friendly way to interact with AWS resources. We could also optionally set up Multi Factor Authentication and a minimum password strength
  
## Permissions
- Idea: assign IAM users to IAM groups. IAM policies (not to be confused with SCP policies) can then be attached to groups, and the permissions granted by these policies will be granted to all users in the group. 
- Create one group for all GiPHouse employees, since all teams and all members should probably have the same permissions. 
- If some teams or specific members in teams end up needing more permissions, they could also be assigned to another IAM group which grants these permissions (one IAM user can be assigned to 10 groups).
- Because GiPHouse employees are able to log into the mailing list member account, we have to make sure that permissions for this account are correct. Because a member account is not an IAM user, we cannot attach IAM policies to it. We have to manage this account's permissions with SCP policies, and can then configure the IAM policies such that the IAM users have exactly the same permissions as the member account they are under. Because the effective permissions are the logical intersection between what is allowed by SCP and what is allowed by IAM (see https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html), it should suffice to correctly set up the SCP permissions and allow everything for IAM users; the logical intersection will then be only the SCP permissions. 

## Implementation
Use boto3 IAM client, see https://boto3.amazonaws.com/v1/documentation/api/1.14.0/reference/services/iam.html?highlight=iam.

# Research
## IAM Users
Source for following 4 sections: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users.html

### Identification
- IAM user identified in three ways:
  - Friendly name: display name
  - Amazon Resource Name (ARN): used for identifying IAM user accross all of AWS
  - IAM user ID: unique per IAM user, but AWS recommends using the ARN to identify user
  
### Credentials
- How IAM users access AWS depends on their credentials:
  - Console password to log in to the AWS management console
  - Access keys to make programmatic calls to AWS, but long term access keys are not considered secure; see https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#alternatives-to-long-term-access-keys
  - SSH keys for access to CodeCommit, private git repos in AWS cloud
  - Server certificates used to authenticate with some AWS services. AWS recommends using AWS Certificate Manager (ACM) for this instead of IAM, only use IAM when ACM not available in your region (it is available in Ireland)
- Options for credentials:
  - Console passwords and access keys can be created and changed.
  - Passwords: set minimum password strength policy, allow users to change passwords
  - Multi Factor Authentication recommended as a best practice
  - AWS recommends removing passwords and access keys when users no longer need them (in our case, at the end of the course, but this may be out of scope for our project)
  - I think giving students a console password would be best, the AWS management console seems to be the general hub for AWS-related tasks, and I would guess it is the most user-friendly since it is a web application
  

### Permissions
- By default, IAM user has no permissions
- Amazon recommends principle of least privilege: give each user only the permissions they need to perform the required tasks

### Account
- Each IAM user is linked to one AWS account
- IAM user activities are billed to the linked AWS account
  
### Creating IAM users
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html
- Using API to create IAM user:
  1. create credentials (e.g. password/access key): AWS recommends only creating the credentials which the user needs
  2. Give users permissions: can be done by attaching *policies* to user directly, or adding user to an already existing *group* (second is recommended). See IAM groups and Policies sections for more information
  3. Optional: attach tags to user, see https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html
  4. Provide sign-in info to user: login URL, credentials. Optionally, set up MFA and allow user to change their own credentials

### Changing IAM user permissions
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_change-permissions.html
- IAM user permissions can be changed by:
  - Changing which groups the user is a member of
  - Copying permissisions from another user
  - Attaching a policy directly

## IAM groups
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_groups.html
- IAM groups can contain multiple IAM users. Attaching a policy to an IAM groups means you attach it to all users.
- Can not be nested, meaning no IAM group containing another IAM group.
- Limitations: 300 groups per AWS account, IAM user can be part of 10 groups
- Idea: IAM group for all students. This gives all users same permissions. Then also put students in separate groups for edge cases where extra permissions are necessary.

## IAM roles
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html

Can be used to grant temporary extra permissions to IAM users, but seems out of scope for our project.

## Policies (different from SCP policies)
- Object which can be attached to an identity/resource to define its permissions
- Two types
  - Identity-based policy: attach to e.g. IAM user/group to specify what they can do
  - Resource-based policy: attach to resource to specify who can access it.
- Permission boundaries: extra policy which sets the maximum features granted by another policy. Seems unnecessary as we can do the same thing with SCP policies. See https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html
  
## IAM implementation
https://boto3.amazonaws.com/v1/documentation/api/1.14.0/reference/services/iam.html?highlight=iam

## Interaction between IAM and SCP
- IAM grants permissions, while SCP denies permissions 
- SCP overwrites IAM: if SCP denies some permission while IAM grants it, the permission is denied

## Should we implement IAM users in our project? 
- TODO
