### ISSUE TITLE
Resolve security flaw when creating member account

### ISSUE THREAD

**Issue by Fiflakos** [GiPHouse/giphouse-website-spring2023#61]
**One-sentence description**

Resolve security flaw when creating member accounts

**Description**
The point of the task is to prevent member accounts from having all rights before they are moved to their course iteration OU.

**Suggested implementation**

The implementation is to add the tag to the member account when creating it, and removing the tag once the member account is moved to the course iteration OU.

**Comment by 1058274** [comment]
Resolved in #68.
