### ISSUE TITLE
Documentation: AWS Integration

### ISSUE THREAD

**Issue by 1058274** [GiPHouse/giphouse-website-spring2023#63]
### One-sentence description

Add AWS integration documentation to `/README.md`.

### Motivation

The users/developers of the system should have an idea on what the newly added features do without having to inspect the code.

### Suggest implementation
- Explain what the new AWS integration feature offers
- Explain how the synchronization process works between GiPHouse and AWS environments
- Other important implementation details

**Comment by BheeshmasenaReddy** [comment]
Hi @1058274 , I would like to work on this, could you please assign me this issue and give some details about resources to refer for the topic and inclusions. I am a beginner in AWS, recently completed practitioner cert and looking for some projects to contribute.

**Comment by 1058274** [comment]
> Hi @1058274 , I would like to work on this, could you please assign me this issue and give some details about resources to refer for the topic and inclusions. I am a beginner in AWS, recently completed practitioner cert and looking for some projects to contribute.

Awesome that you want to contribute! This is a forked repository that extends the main framework of a few university courses related to collaborative software engineering. In fact, this repository is the work of a team of students (including myself) as part of one of the courses.

As for whether you can get this issue assigned: no because I am already working on it and I doubt that you, without having worked on the new feature, will be able to provide accurate descriptions for documentation on what this forked repository adds with respect to the original repository.

However, feel free and encouraged to look at the development branch to see if you can find any important new issues that need to be addressed, and create a Github issue for it to discuss :). Note that this project might not be the best for you to contribute to as of now, because the course is coming to an end in a few weeks. Should this repository get merged with the original repository, however, then it might be more suited to contribute to for you, should you wish to.
