### ISSUE TITLE
Resolve unneeded tags which are still used

### ISSUE THREAD

**Issue by flam123** [GiPHouse/giphouse-website-spring2023#64]
After looking into the source code of this repository, I see that the tags: project_slug, project_semester and project_email are used but not necessary in this case.

**Comment by flam123** [comment]
project_slug and project_semester are used in the following account:
	get_syncdata_from_giphouse
	extract_aws_setup
	create_and_move_account
	
In get_syncdata_from_giphouse the project_slug, project_semester and project_email tag is extracted from giphouse website and put as a syncdata list.
In extract_aws_setup, users are filtered on the project_slug and project_semester tag. In create_and_move account, accounts are created with the project_slug and project_semester attached

**Comment by flam123** [comment]
It looks like only the email tag is used for creating accounts, the moving of account does not use the project_semester as destination id. But after creating the account. It is not necessary keeping the tags in those accounts.

**Comment by 1058274** [comment]
Resolved in https://github.com/GiPHouse/giphouse-website-spring2023/commit/bc1316552aa7da90b9d4650b7cfdd4ad6264033a.
